type ChemicalElement = Readonly<{
  name: string;
  atomic_mass: number;
  number: number;
  period: number;
  group: number;
  symbol: string;
  block: string;
}>;

export const chemicalElements: readonly ChemicalElement[] = [
  {
    name: "Hydrogen",
    atomic_mass: 1.008,
    number: 1,
    period: 1,
    group: 1,
    symbol: "H",
    block: "s",
  },
  {
    name: "Helium",
    atomic_mass: 4.0026022,
    number: 2,
    period: 1,
    group: 18,
    symbol: "He",
    block: "s",
  },
  {
    name: "Lithium",
    atomic_mass: 6.94,
    number: 3,
    period: 2,
    group: 1,
    symbol: "Li",
    block: "s",
  },
  {
    name: "Beryllium",
    atomic_mass: 9.01218315,
    number: 4,
    period: 2,
    group: 2,
    symbol: "Be",
    block: "s",
  },
  {
    name: "Boron",
    atomic_mass: 10.81,
    number: 5,
    period: 2,
    group: 13,
    symbol: "B",
    block: "p",
  },
  {
    name: "Carbon",
    atomic_mass: 12.011,
    number: 6,
    period: 2,
    group: 14,
    symbol: "C",
    block: "p",
  },
  {
    name: "Nitrogen",
    atomic_mass: 14.007,
    number: 7,
    period: 2,
    group: 15,
    symbol: "N",
    block: "p",
  },
  {
    name: "Oxygen",
    atomic_mass: 15.999,
    number: 8,
    period: 2,
    group: 16,
    symbol: "O",
    block: "p",
  },
  {
    name: "Fluorine",
    atomic_mass: 18.9984031636,
    number: 9,
    period: 2,
    group: 17,
    symbol: "F",
    block: "p",
  },
  {
    name: "Neon",
    atomic_mass: 20.17976,
    number: 10,
    period: 2,
    group: 18,
    symbol: "Ne",
    block: "p",
  },
  {
    name: "Sodium",
    atomic_mass: 22.989769282,
    number: 11,
    period: 3,
    group: 1,
    symbol: "Na",
    block: "s",
  },
  {
    name: "Magnesium",
    atomic_mass: 24.305,
    number: 12,
    period: 3,
    group: 2,
    symbol: "Mg",
    block: "s",
  },
  {
    name: "Aluminium",
    atomic_mass: 26.98153857,
    number: 13,
    period: 3,
    group: 13,
    symbol: "Al",
    block: "p",
  },
  {
    name: "Silicon",
    atomic_mass: 28.085,
    number: 14,
    period: 3,
    group: 14,
    symbol: "Si",
    block: "p",
  },
  {
    name: "Phosphorus",
    atomic_mass: 30.9737619985,
    number: 15,
    period: 3,
    group: 15,
    symbol: "P",
    block: "p",
  },
  {
    name: "Sulfur",
    atomic_mass: 32.06,
    number: 16,
    period: 3,
    group: 16,
    symbol: "S",
    block: "p",
  },
  {
    name: "Chlorine",
    atomic_mass: 35.45,
    number: 17,
    period: 3,
    group: 17,
    symbol: "Cl",
    block: "p",
  },
  {
    name: "Argon",
    atomic_mass: 39.9481,
    number: 18,
    period: 3,
    group: 18,
    symbol: "Ar",
    block: "p",
  },
  {
    name: "Potassium",
    atomic_mass: 39.09831,
    number: 19,
    period: 4,
    group: 1,
    symbol: "K",
    block: "s",
  },
  {
    name: "Calcium",
    atomic_mass: 40.0784,
    number: 20,
    period: 4,
    group: 2,
    symbol: "Ca",
    block: "s",
  },
  {
    name: "Scandium",
    atomic_mass: 44.9559085,
    number: 21,
    period: 4,
    group: 3,
    symbol: "Sc",
    block: "d",
  },
  {
    name: "Titanium",
    atomic_mass: 47.8671,
    number: 22,
    period: 4,
    group: 4,
    symbol: "Ti",
    block: "d",
  },
  {
    name: "Vanadium",
    atomic_mass: 50.94151,
    number: 23,
    period: 4,
    group: 5,
    symbol: "V",
    block: "d",
  },
  {
    name: "Chromium",
    atomic_mass: 51.99616,
    number: 24,
    period: 4,
    group: 6,
    symbol: "Cr",
    block: "d",
  },
  {
    name: "Manganese",
    atomic_mass: 54.9380443,
    number: 25,
    period: 4,
    group: 7,
    symbol: "Mn",
    block: "d",
  },
  {
    name: "Iron",
    atomic_mass: 55.8452,
    number: 26,
    period: 4,
    group: 8,
    symbol: "Fe",
    block: "d",
  },
  {
    name: "Cobalt",
    atomic_mass: 58.9331944,
    number: 27,
    period: 4,
    group: 9,
    symbol: "Co",
    block: "d",
  },
  {
    name: "Nickel",
    atomic_mass: 58.69344,
    number: 28,
    period: 4,
    group: 10,
    symbol: "Ni",
    block: "d",
  },
  {
    name: "Copper",
    atomic_mass: 63.5463,
    number: 29,
    period: 4,
    group: 11,
    symbol: "Cu",
    block: "d",
  },
  {
    name: "Zinc",
    atomic_mass: 65.382,
    number: 30,
    period: 4,
    group: 12,
    symbol: "Zn",
    block: "d",
  },
  {
    name: "Gallium",
    atomic_mass: 69.7231,
    number: 31,
    period: 4,
    group: 13,
    symbol: "Ga",
    block: "p",
  },
  {
    name: "Germanium",
    atomic_mass: 72.6308,
    number: 32,
    period: 4,
    group: 14,
    symbol: "Ge",
    block: "p",
  },
  {
    name: "Arsenic",
    atomic_mass: 74.9215956,
    number: 33,
    period: 4,
    group: 15,
    symbol: "As",
    block: "p",
  },
  {
    name: "Selenium",
    atomic_mass: 78.9718,
    number: 34,
    period: 4,
    group: 16,
    symbol: "Se",
    block: "p",
  },
  {
    name: "Bromine",
    atomic_mass: 79.904,
    number: 35,
    period: 4,
    group: 17,
    symbol: "Br",
    block: "p",
  },
  {
    name: "Krypton",
    atomic_mass: 83.7982,
    number: 36,
    period: 4,
    group: 18,
    symbol: "Kr",
    block: "p",
  },
  {
    name: "Rubidium",
    atomic_mass: 85.46783,
    number: 37,
    period: 5,
    group: 1,
    symbol: "Rb",
    block: "s",
  },
  {
    name: "Strontium",
    atomic_mass: 87.621,
    number: 38,
    period: 5,
    group: 2,
    symbol: "Sr",
    block: "s",
  },
  {
    name: "Yttrium",
    atomic_mass: 88.905842,
    number: 39,
    period: 5,
    group: 3,
    symbol: "Y",
    block: "d",
  },
  {
    name: "Zirconium",
    atomic_mass: 91.2242,
    number: 40,
    period: 5,
    group: 4,
    symbol: "Zr",
    block: "d",
  },
  {
    name: "Niobium",
    atomic_mass: 92.906372,
    number: 41,
    period: 5,
    group: 5,
    symbol: "Nb",
    block: "d",
  },
  {
    name: "Molybdenum",
    atomic_mass: 95.951,
    number: 42,
    period: 5,
    group: 6,
    symbol: "Mo",
    block: "d",
  },
  {
    name: "Technetium",
    atomic_mass: 98,
    number: 43,
    period: 5,
    group: 7,
    symbol: "Tc",
    block: "d",
  },
  {
    name: "Ruthenium",
    atomic_mass: 101.072,
    number: 44,
    period: 5,
    group: 8,
    symbol: "Ru",
    block: "d",
  },
  {
    name: "Rhodium",
    atomic_mass: 102.905502,
    number: 45,
    period: 5,
    group: 9,
    symbol: "Rh",
    block: "d",
  },
  {
    name: "Palladium",
    atomic_mass: 106.421,
    number: 46,
    period: 5,
    group: 10,
    symbol: "Pd",
    block: "d",
  },
  {
    name: "Silver",
    atomic_mass: 107.86822,
    number: 47,
    period: 5,
    group: 11,
    symbol: "Ag",
    block: "d",
  },
  {
    name: "Cadmium",
    atomic_mass: 112.4144,
    number: 48,
    period: 5,
    group: 12,
    symbol: "Cd",
    block: "d",
  },
  {
    name: "Indium",
    atomic_mass: 114.8181,
    number: 49,
    period: 5,
    group: 13,
    symbol: "In",
    block: "p",
  },
  {
    name: "Tin",
    atomic_mass: 118.7107,
    number: 50,
    period: 5,
    group: 14,
    symbol: "Sn",
    block: "p",
  },
  {
    name: "Antimony",
    atomic_mass: 121.7601,
    number: 51,
    period: 5,
    group: 15,
    symbol: "Sb",
    block: "p",
  },
  {
    name: "Tellurium",
    atomic_mass: 127.603,
    number: 52,
    period: 5,
    group: 16,
    symbol: "Te",
    block: "p",
  },
  {
    name: "Iodine",
    atomic_mass: 126.904473,
    number: 53,
    period: 5,
    group: 17,
    symbol: "I",
    block: "p",
  },
  {
    name: "Xenon",
    atomic_mass: 131.2936,
    number: 54,
    period: 5,
    group: 18,
    symbol: "Xe",
    block: "p",
  },
  {
    name: "Cesium",
    atomic_mass: 132.905451966,
    number: 55,
    period: 6,
    group: 1,
    symbol: "Cs",
    block: "s",
  },
  {
    name: "Barium",
    atomic_mass: 137.3277,
    number: 56,
    period: 6,
    group: 2,
    symbol: "Ba",
    block: "s",
  },
  {
    name: "Lanthanum",
    atomic_mass: 138.905477,
    number: 57,
    period: 6,
    group: 3,
    symbol: "La",
    block: "f",
  },
  {
    name: "Cerium",
    atomic_mass: 140.1161,
    number: 58,
    period: 6,
    group: 3,
    symbol: "Ce",
    block: "f",
  },
  {
    name: "Praseodymium",
    atomic_mass: 140.907662,
    number: 59,
    period: 6,
    group: 3,
    symbol: "Pr",
    block: "f",
  },
  {
    name: "Neodymium",
    atomic_mass: 144.2423,
    number: 60,
    period: 6,
    group: 3,
    symbol: "Nd",
    block: "f",
  },
  {
    name: "Promethium",
    atomic_mass: 145,
    number: 61,
    period: 6,
    group: 3,
    symbol: "Pm",
    block: "f",
  },
  {
    name: "Samarium",
    atomic_mass: 150.362,
    number: 62,
    period: 6,
    group: 3,
    symbol: "Sm",
    block: "f",
  },
  {
    name: "Europium",
    atomic_mass: 151.9641,
    number: 63,
    period: 6,
    group: 3,
    symbol: "Eu",
    block: "f",
  },
  {
    name: "Gadolinium",
    atomic_mass: 157.253,
    number: 64,
    period: 6,
    group: 3,
    symbol: "Gd",
    block: "f",
  },
  {
    name: "Terbium",
    atomic_mass: 158.925352,
    number: 65,
    period: 6,
    group: 3,
    symbol: "Tb",
    block: "f",
  },
  {
    name: "Dysprosium",
    atomic_mass: 162.5001,
    number: 66,
    period: 6,
    group: 3,
    symbol: "Dy",
    block: "f",
  },
  {
    name: "Holmium",
    atomic_mass: 164.930332,
    number: 67,
    period: 6,
    group: 3,
    symbol: "Ho",
    block: "f",
  },
  {
    name: "Erbium",
    atomic_mass: 167.2593,
    number: 68,
    period: 6,
    group: 3,
    symbol: "Er",
    block: "f",
  },
  {
    name: "Thulium",
    atomic_mass: 168.934222,
    number: 69,
    period: 6,
    group: 3,
    symbol: "Tm",
    block: "f",
  },
  {
    name: "Ytterbium",
    atomic_mass: 173.0451,
    number: 70,
    period: 6,
    group: 3,
    symbol: "Yb",
    block: "f",
  },
  {
    name: "Lutetium",
    atomic_mass: 174.96681,
    number: 71,
    period: 6,
    group: 3,
    symbol: "Lu",
    block: "d",
  },
  {
    name: "Hafnium",
    atomic_mass: 178.492,
    number: 72,
    period: 6,
    group: 4,
    symbol: "Hf",
    block: "d",
  },
  {
    name: "Tantalum",
    atomic_mass: 180.947882,
    number: 73,
    period: 6,
    group: 5,
    symbol: "Ta",
    block: "d",
  },
  {
    name: "Tungsten",
    atomic_mass: 183.841,
    number: 74,
    period: 6,
    group: 6,
    symbol: "W",
    block: "d",
  },
  {
    name: "Rhenium",
    atomic_mass: 186.2071,
    number: 75,
    period: 6,
    group: 7,
    symbol: "Re",
    block: "d",
  },
  {
    name: "Osmium",
    atomic_mass: 190.233,
    number: 76,
    period: 6,
    group: 8,
    symbol: "Os",
    block: "d",
  },
  {
    name: "Iridium",
    atomic_mass: 192.2173,
    number: 77,
    period: 6,
    group: 9,
    symbol: "Ir",
    block: "d",
  },
  {
    name: "Platinum",
    atomic_mass: 195.0849,
    number: 78,
    period: 6,
    group: 10,
    symbol: "Pt",
    block: "d",
  },
  {
    name: "Gold",
    atomic_mass: 196.9665695,
    number: 79,
    period: 6,
    group: 11,
    symbol: "Au",
    block: "d",
  },
  {
    name: "Mercury",
    atomic_mass: 200.5923,
    number: 80,
    period: 6,
    group: 12,
    symbol: "Hg",
    block: "d",
  },
  {
    name: "Thallium",
    atomic_mass: 204.38,
    number: 81,
    period: 6,
    group: 13,
    symbol: "Tl",
    block: "p",
  },
  {
    name: "Lead",
    atomic_mass: 207.21,
    number: 82,
    period: 6,
    group: 14,
    symbol: "Pb",
    block: "p",
  },
  {
    name: "Bismuth",
    atomic_mass: 208.980401,
    number: 83,
    period: 6,
    group: 15,
    symbol: "Bi",
    block: "p",
  },
  {
    name: "Polonium",
    atomic_mass: 209,
    number: 84,
    period: 6,
    group: 16,
    symbol: "Po",
    block: "p",
  },
  {
    name: "Astatine",
    atomic_mass: 210,
    number: 85,
    period: 6,
    group: 17,
    symbol: "At",
    block: "p",
  },
  {
    name: "Radon",
    atomic_mass: 222,
    number: 86,
    period: 6,
    group: 18,
    symbol: "Rn",
    block: "p",
  },
  {
    name: "Francium",
    atomic_mass: 223,
    number: 87,
    period: 7,
    group: 1,
    symbol: "Fr",
    block: "s",
  },
  {
    name: "Radium",
    atomic_mass: 226,
    number: 88,
    period: 7,
    group: 2,
    symbol: "Ra",
    block: "s",
  },
  {
    name: "Actinium",
    atomic_mass: 227,
    number: 89,
    period: 7,
    group: 3,
    symbol: "Ac",
    block: "f",
  },
  {
    name: "Thorium",
    atomic_mass: 232.03774,
    number: 90,
    period: 7,
    group: 3,
    symbol: "Th",
    block: "f",
  },
  {
    name: "Protactinium",
    atomic_mass: 231.035882,
    number: 91,
    period: 7,
    group: 3,
    symbol: "Pa",
    block: "f",
  },
  {
    name: "Uranium",
    atomic_mass: 238.028913,
    number: 92,
    period: 7,
    group: 3,
    symbol: "U",
    block: "f",
  },
  {
    name: "Neptunium",
    atomic_mass: 237,
    number: 93,
    period: 7,
    group: 3,
    symbol: "Np",
    block: "f",
  },
  {
    name: "Plutonium",
    atomic_mass: 244,
    number: 94,
    period: 7,
    group: 3,
    symbol: "Pu",
    block: "f",
  },
  {
    name: "Americium",
    atomic_mass: 243,
    number: 95,
    period: 7,
    group: 3,
    symbol: "Am",
    block: "f",
  },
  {
    name: "Curium",
    atomic_mass: 247,
    number: 96,
    period: 7,
    group: 3,
    symbol: "Cm",
    block: "f",
  },
  {
    name: "Berkelium",
    atomic_mass: 247,
    number: 97,
    period: 7,
    group: 3,
    symbol: "Bk",
    block: "f",
  },
  {
    name: "Californium",
    atomic_mass: 251,
    number: 98,
    period: 7,
    group: 3,
    symbol: "Cf",
    block: "f",
  },
  {
    name: "Einsteinium",
    atomic_mass: 252,
    number: 99,
    period: 7,
    group: 3,
    symbol: "Es",
    block: "f",
  },
  {
    name: "Fermium",
    atomic_mass: 257,
    number: 100,
    period: 7,
    group: 3,
    symbol: "Fm",
    block: "f",
  },
  {
    name: "Mendelevium",
    atomic_mass: 258,
    number: 101,
    period: 7,
    group: 3,
    symbol: "Md",
    block: "f",
  },
  {
    name: "Nobelium",
    atomic_mass: 259,
    number: 102,
    period: 7,
    group: 3,
    symbol: "No",
    block: "f",
  },
  {
    name: "Lawrencium",
    atomic_mass: 266,
    number: 103,
    period: 7,
    group: 3,
    symbol: "Lr",
    block: "d",
  },
  {
    name: "Rutherfordium",
    atomic_mass: 267,
    number: 104,
    period: 7,
    group: 4,
    symbol: "Rf",
    block: "d",
  },
  {
    name: "Dubnium",
    atomic_mass: 268,
    number: 105,
    period: 7,
    group: 5,
    symbol: "Db",
    block: "d",
  },
  {
    name: "Seaborgium",
    atomic_mass: 269,
    number: 106,
    period: 7,
    group: 6,
    symbol: "Sg",
    block: "d",
  },
  {
    name: "Bohrium",
    atomic_mass: 270,
    number: 107,
    period: 7,
    group: 7,
    symbol: "Bh",
    block: "d",
  },
  {
    name: "Hassium",
    atomic_mass: 269,
    number: 108,
    period: 7,
    group: 8,
    symbol: "Hs",
    block: "d",
  },
  {
    name: "Meitnerium",
    atomic_mass: 278,
    number: 109,
    period: 7,
    group: 9,
    symbol: "Mt",
    block: "d",
  },
  {
    name: "Darmstadtium",
    atomic_mass: 281,
    number: 110,
    period: 7,
    group: 10,
    symbol: "Ds",
    block: "d",
  },
  {
    name: "Roentgenium",
    atomic_mass: 282,
    number: 111,
    period: 7,
    group: 11,
    symbol: "Rg",
    block: "d",
  },
  {
    name: "Copernicium",
    atomic_mass: 285,
    number: 112,
    period: 7,
    group: 12,
    symbol: "Cn",
    block: "d",
  },
  {
    name: "Nihonium",
    atomic_mass: 286,
    number: 113,
    period: 7,
    group: 13,
    symbol: "Nh",
    block: "p",
  },
  {
    name: "Flerovium",
    atomic_mass: 289,
    number: 114,
    period: 7,
    group: 14,
    symbol: "Fl",
    block: "p",
  },
  {
    name: "Moscovium",
    atomic_mass: 289,
    number: 115,
    period: 7,
    group: 15,
    symbol: "Mc",
    block: "p",
  },
  {
    name: "Livermorium",
    atomic_mass: 293,
    number: 116,
    period: 7,
    group: 16,
    symbol: "Lv",
    block: "p",
  },
  {
    name: "Tennessine",
    atomic_mass: 294,
    number: 117,
    period: 7,
    group: 17,
    symbol: "Ts",
    block: "p",
  },
  {
    name: "Oganesson",
    atomic_mass: 294,
    number: 118,
    period: 7,
    group: 18,
    symbol: "Og",
    block: "p",
  },
  {
    name: "Ununennium",
    atomic_mass: 315,
    number: 119,
    period: 8,
    group: 1,
    symbol: "Uue",
    block: "s",
  },
];
