name: check

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
      - name: Install
        run: pnpm install
      - name: Prettier
        run: pnpm prettier:check
      - name: Build
        run: pnpm build
