name: check

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
      - name: prettier
        run: pnpm run prettier:check
